apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: read-only-role
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log", "services", "endpoints", "nodes", "configmaps"]
  verbs: ["get", "list", "watch"]
